[project]
name = "ingest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "influxdb-client>=1.50.0",
    "requests>=2.32.5",
    "ruff>=0.15.0",
    "schedule>=1.2.2",
]
